"""Create transaction table.

Revision ID: 034e8c573243
Revises: b48c376435ee
Create Date: 2025-06-11 15:56:43.289741

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '034e8c573243'
down_revision: Union[str, None] = 'b48c376435ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'transactions',
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('actif_a', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('qty_a', sa.Float(), nullable=False),
        sa.Column('actif_v', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('actif_f', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('qty_f', sa.Float(), nullable=True),
        sa.Column('value_f', sa.Float(), nullable=True),
        sa.Column('value_a', sa.Float(), nullable=True),
        sa.Column('uid', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['actif_a'],
            ['tokens.cg_id'],
        ),
        sa.ForeignKeyConstraint(
            ['actif_f'],
            ['tokens.cg_id'],
        ),
        sa.ForeignKeyConstraint(
            ['actif_v'],
            ['tokens.cg_id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.uid'],
        ),
        sa.PrimaryKeyConstraint('uid'),
    )
    op.create_index(
        op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
