"""Create transaction table.

Revision ID: 0e99e6b88449
Revises: c7b3f42daeef
Create Date: 2025-06-12 11:44:31.878868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e99e6b88449'
down_revision: Union[str, None] = 'c7b3f42daeef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty_a', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qty_f', sa.Float(), nullable=True),
    sa.Column('value_f', sa.Float(), nullable=True),
    sa.Column('value_a', sa.Float(), nullable=True),
    sa.Column('actif_a_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actif_v_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actif_f_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['actif_a_id'], ['tokens.cg_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actif_f_id'], ['tokens.cg_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actif_v_id'], ['tokens.cg_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
